### ISSUE TITLE
ASP.NET v5 Core & Framework v4.6 targeting?

### ISSUE THREAD

**Issue by Jeavon** [nuproj/nuproj#168]
When adding a reference to a project targeting ASP.NET v5.0 Core and Framework v4.6 I get the following error:

	Severity	Code	Description	Project	File	Line
	Error	MSB4018	The "AssignTargetFramework" task failed unexpectedly.
	System.ArgumentException: Value cannot be null or an empty string.
	Parameter name: profileValue
	   at NuGet.NetPortableProfile.Parse(String profileValue, Boolean treatOptionalFrameworksAsSupportedFrameworks)
	   at NuGet.VersionUtility.GetShortFrameworkName(FrameworkName frameworkName)
	   at NuProj.Tasks.Extensions.GetShortFrameworkName(FrameworkName frameworkName)
	   at NuProj.Tasks.AssignTargetFramework.ConvertToPackageFile(ITaskItem output)
	   at System.Linq.Enumerable.<>c__DisplayClass2`3.<CombineSelectors>b__3(TSource x)
	   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
	   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
	   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
	   at NuProj.Tasks.AssignTargetFramework.Execute()
	   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
	   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	ImageProcessor.nupkg	C:\Program Files (x86)\MSBuild\NuProj\NuProj.targets	486

Anyone have any ideas how to fix this?

Thanks!

**Comment by AArnott** [comment]
If this is an xproj, NuProj does not yet support project references to xproj yet.
Likewise, it doesn't support any project (e.g. csproj) that uses project.json. It will work, but it doesn't capture the package dependencies.

**Comment by Jeavon** [comment]
Yes it is a xproj, I'll look forward to support in the future, thanks!
