### ISSUE TITLE
Feature Request: Ability to reference UAP/WinRT C++ projects

### ISSUE THREAD

**Issue by ravensorb** [nuproj/nuproj#179]
I noticed that when I try to add a reference to a WinRT C++ project (it outputs an assembly dll), I get the following error 

    ---------------------------
    Microsoft Visual Studio
    ---------------------------
    Confirm unsupported reference(s)

    One or more of the selected items is not a valid reference for this type of project.  Do you want to continue and add all the references anyway?

**Comment by kovalikp** [comment]
Right now, NuProj is hard-coded to only accept c#, vb or f# https://github.com/nuproj/nuproj/blob/master/src/NuProj.ProjectSystem.12/NuProjValidProjectReferenceChecker.cs#L90

If you could provide me some sample of C++ project with expected NuGet package layout, I would love to have a look at this. Ideally you could prepre a unit test similar to `References_PackageOutputGroups`.

**Comment by ravensorb** [comment]
Yep, I had added the vcxproj to that as I was working through things.

Here is the projects I am trying to get to work with nuproj

https://github.com/XLabs/Xamarin-Forms-Labs/tree/master/src/Platform/XLabs.Platform.WinRT

**Comment by heaths** [comment]
Or even just desktop C++ projects using vcxproj. The `AssignTargetFramework` task fails:

```
Error	MSB4018	The "AssignTargetFramework" task failed unexpectedly.
System.ArgumentNullException: Value cannot be null.
Parameter name: path2
   at System.IO.Path.Combine(String path1, String path2, String path3, String path4)
   at NuProj.Tasks.Extensions.Combine(PackageDirectory packageDirectory, String targetFramework, String packageSubdirectory, String fileName)
   at NuProj.Tasks.AssignTargetFramework.ConvertToPackageFile(ITaskItem output)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NuProj.Tasks.AssignTargetFramework.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```
