### ISSUE TITLE
Beta 11.12 is broken, missing nuget.core.dll in package

### ISSUE THREAD

**Issue by stecydube** [nuproj/nuproj#252]
Also seems to miss nuget.exe

Cannot build nuproj project anymore.

```
proj\packages\NuProj.0.11.12-beta\Tools\NuProj.targets(369,9): error MSB4018: The "AssignTargetFramework" task failed unexpectedly.
proj\packages\NuProj.0.11.12-beta\Tools\NuProj.targets(369,9): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Core, Version=2.11.1.812, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
proj\packages\NuProj.0.11.12-beta\Tools\NuProj.targets(369,9): error MSB4018: File name: 'NuGet.Core, Version=2.11.1.812, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
proj\packages\NuProj.0.11.12-beta\Tools\NuProj.targets(369,9): error MSB4018:    at NuProj.Tasks.Extensions.GetShortFrameworkName(FrameworkName frameworkName)
proj\packages\NuProj.0.11.12-beta\Tools\NuProj.targets(369,9): error MSB4018:    at NuProj.Tasks.AssignTargetFramework.ConvertToPackageFile(ITaskItem output) in C:\projects\nuproj\src\NuProj.Tasks\AssignTargetFramework.cs:line 48
proj\packages\NuProj.0.11.12-beta\Tools\NuProj.targets(369,9): error MSB4018:    at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
proj\packages\NuProj.0.11.12-beta\Tools\NuProj.targets(369,9): error MSB4018:    at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
proj\packages\NuProj.0.11.12-beta\Tools\NuProj.targets(369,9): error MSB4018:    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
proj\packages\NuProj.0.11.12-beta\Tools\NuProj.targets(369,9): error MSB4018:    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
proj\packages\NuProj.0.11.12-beta\Tools\NuProj.targets(369,9): error MSB4018:    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
proj\packages\NuProj.0.11.12-beta\Tools\NuProj.targets(369,9): error MSB4018:    at NuProj.Tasks.AssignTargetFramework.Execute() in C:\projects\nuproj\src\NuProj.Tasks\AssignTargetFramework.cs:line 31
proj\packages\NuProj.0.11.12-beta\Tools\NuProj.targets(369,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
proj\packages\NuProj.0.11.12-beta\Tools\NuProj.targets(369,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

```

**Comment by jmelosegui** [comment]
Duplicated. See #250 for more info.
