### ISSUE TITLE
ReSharper 2017 can no longer build NuGet Package projects

### ISSUE THREAD

**Issue by Infarinato** [nuproj/nuproj#289]
Admittedly, this is probably a ReSharper bug, but I was wondering whether it might have anything to do with some NuGet Package Project known issue, just in case…

Basically, ReSharper 2017 doesn’t seem to be able to build NuGet Package projects anymore (”ReSharper build” — _ReSharper 2016 used to build them fine_). When I try to clean or build _any_ NuGet Package project like the simple one in the solution below…
![solution_structure](https://cloud.githubusercontent.com/assets/365768/25391580/7492b60c-29ce-11e7-9af6-0529a354f2da.png)
… I get the following error message:

>The reference to custom metadata "PackageDirectoryPath" at position 1 is not allowed in this condition "'%(NuGetDependency.PackageDirectoryPath)' != ''".  C:\Applications\Shared\Hcc.Utils\Hcc.Utils.EPayments\Hcc.Utils.EPayments.nuproj
at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
at Microsoft.Build.Evaluation.Parser.Parse(String expression, ParserOptions optionSettings, ElementLocation elementLocation)
at Microsoft.Build.Evaluation.ConditionEvaluator.EvaluateConditionCollectingConditionedProperties[P,I](String condition, ParserOptions options, Expander\`2 expander, ExpanderOptions expanderOptions, Dictionary\`2 conditionedPropertiesTable, String evaluationDirectory, ElementLocation elementLocation, ILoggingService loggingServices, BuildEventContext buildEventContext, ProjectRootElementCache projectRootElementCache)
at Microsoft.Build.Execution.ProjectInstance.EvaluateCondition(String condition)
at JetBrains.Platform.MsBuild.TaskCommon.ProjectModel.Bindings.AddWildcardItemsFromXml(ProjectRootElement element, Boolean isImported, ProjectInstance projectInstance, List\`1 items)
at JetBrains.Platform.MsBuild.TaskCommon.ProjectModel.Bindings.BindWildcardItems(Project project, ProjectInstance projectInstance)
at JetBrains.Platform.MsBuild.TaskCommon.ProjectModel.Bindings.Bind(Project project, ProjectInstance projectInstance, List\`1 targetErrors, List\`1 targetWarnings, Dictionary\`2 resultsByTarget)
at JetBrains.Platform.MsBuild.TaskCommon.ProjectModel.Bindings.Bind(Project project, ProjectInstance projectInstance)
at JetBrains.Platform.MsBuild.TaskCommon.Build.BuildSessionHost.HandleSubmissionFinished(RdBuildRequest request, ProjectWithEvents projectWithEvents, Boolean succeeded, RdTask\`1 rdTask)

Any ideas?

Many thanks,

Paolo

**System details**
`Microsoft Visual Studio Enterprise 2015`
`Version 14.0.25431.01 Update 3`
`Microsoft .NET Framework`
`Version 4.6.01590`

`JetBrains ReSharper Ultimate 2017.1.1    Build 108.0.20170407.122957`
(_ReSharper 2016.3.2 was fine_)

`NuGet Package Project for Visual Studio 2015    Version 0.11.14.26195`

**Comment by AArnott** [comment]
Are you talking about Resharper's *IDE* or its VS extension? Your screenshot looks an awful lot like VS but your description sounds like VS mostly.

I suspect you may have a fancy Unicode character in the expression that *looks* ok but isn't a standard ascii character that MSBuild is expecting.

**Comment by Infarinato** [comment]
Thank you very much for your quick reply, Andrew. :-)

I’m talking about the ReSharper (2017) extension for Visual Studio (2015, in my case).

![resharper_build](https://cloud.githubusercontent.com/assets/365768/25393899/abb9b5e4-29d4-11e7-95f2-bed5a2e7259a.png)

…and don’t think I’ve got any fancy Unicode character anywhere!

**Comment by AArnott** [comment]
Well, if you can build using VS build or from the command line, but ReSharper's build fails, then yes, please file a bug against Resharper.

**Comment by Infarinato** [comment]
Apparently, someone has already done it: https://youtrack.jetbrains.com/issue/RSRP-464192. :-)
