### ISSUE TITLE
NuProj for VS 2017 fails to build in AssignTargetFramework task

### ISSUE THREAD

**Issue by dmalanij** [nuproj/nuproj#297]
Taking over from the comment in #266. 

I've installed the [just published extension](https://marketplace.visualstudio.com/items?itemName=NuProjTeam.NuProj2017), the vsix manifest information is as follows:
* id: NuProj.15
* version: 0.20.9.13653

Unfortunately, is not working. At least not for me in 3 different computers (including one where Nuproj for VS2015 used to work perfectly fine). Even if nuproj files open correctly, when building they fail with: 
```
MSB4018	The "AssignTargetFramework" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Frameworks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. El sistema no puede encontrar el archivo especificado.
File name: 'NuGet.Frameworks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at NuProj.Tasks.AssignTargetFramework.ConvertToPackageFile(ITaskItem output)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NuProj.Tasks.AssignTargetFramework.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```
And the source points to 

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\NuProj\NuProj.targets	376	
```

As per the environment configuration:
* 2 machines with Windows 10.1 Pro and VS 2017 Professional
* 1 machine with Windows 10.1 Home and VS 2017 Community

Tomorrow I'll try to take a look with more detail with the fusion log. So far, I'm reporting this so you are aware and can take a look to.

**Comment by dmalanij** [comment]
Ok. with the help of the Fusion log I was able to get it working. However I believe is a big and dangerous workaround. What I did was taking some Nuget dlls from their published packages and store them in the nuproj installation path. The packages I had to take those from are:
- NuGet.Frameworks
- NuGet.Packaging.Core
- NuGet.Packaging.Core.Types
- NuGet.Packaging
- NuGet.Versioning

All of them with version 4.0.0

From the Fusion Log I can see that probed paths were:
- C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
- C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Nuproj

Hope this helps you to find a more proper solution. Cheers

**Comment by Kolky** [comment]
@dmalanij that trick worked aswell for me, however an official solution would be nice!

**Comment by BjoernHund** [comment]
We have the same problem with the current version of `nuproj`

**Comment by tnt-7** [comment]
I had to uninstall Nuproj for VS2017 extension and it worked fine with CLI.

**Comment by Siderite** [comment]
In order to make the extension work for 2017 (at least for the project that I had) follow these steps:
- download source from https://github.com/nuproj/nuproj
- open src/NuProj.sln with Visual Studio 2017
- remove projects NuProj.ProjectSystem.12, NuProj.ProjectSystem.14 and NuProj.Setup
- build the project
- right-click on NuProj.ProjectSystem.15 and add a new folder called NuProj
- right-click on the NuProj folder and add (use Add as Link!! the little arrow on the Add button in the dialog) existing items from the bin/Debug folder of the NuProj.Tasks project:
           NuGet.Frameworks.dll
           NuGet.Packaging.dll
           NuGet.Packaging.Core.dll
           NuGet.Packaging.Core.Types.dll
           NuGet.Versioning.dll
- select the five files and change:
           Install Root to MSBuild
           Include in VSIX to True
- open Solution items -> version.json and change version from what it is (ex: 0.20-beta) to something larger (0.26) - optional, but it will stop saying you need to update and if you have your local nuget server it will tell you to update the one you have
- rebuild (not just build) solution
The resulting .vsix file (src\NuProj.ProjectSystem.15\bin\Debug\NuProj.ProjectSystem.15.vsix) is the extension that allows using .nuproj in VS2017

The packages are somewhat obsolete, but you can right click the solution and managing the nuget packages and selecting them all for update. In this case, if you upgrade NuGet, you will not need  NuGet.Packaging.Core.Types anymore.

This solution gets you the working vsix, but disables completely the batch file system of building and installing. It works only from within VS2017.

**Comment by rodro75** [comment]
Same problem for me.
I have both VS2015 Community AND VS2017 Community installed.
The solution suggested by @dmalanij worked for me: I copied the assemblies only in `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Nuproj` folder.

**Comment by joepeavey** [comment]
WTF why hasn't this been updated in the latest release already?

**Comment by joepeavey** [comment]
> Ok. with the help of the Fusion log I was able to get it working. However I believe is a big and dangerous workaround. What I did was taking some Nuget dlls from their published packages and store them in the nuproj installation path. The packages I had to take those from are:
> 
> * NuGet.Frameworks
> * NuGet.Packaging.Core
> * NuGet.Packaging.Core.Types
> * NuGet.Packaging
> * NuGet.Versioning
> 
> All of them with version 4.0.0
> 
> From the Fusion Log I can see that probed paths were:
> 
> * C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
> * C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Nuproj
> 
> Hope this helps you to find a more proper solution. Cheers

DOES ANYONE HAVE THE CORRECT FILES THAT THEY CAN SHARE? FINDING THE CORRECT VERSION IS A NIGHTMARE....

**Comment by dmalanij** [comment]
@joepeavey It's not that difficult. Here is a detailed step list 

1. Download the nuget packages. Just to avoid you the search in the repository here you have the links:
    - https://www.nuget.org/packages/NuGet.Packaging/4.0.0
    - https://www.nuget.org/packages/NuGet.Packaging.Core/4.0.0
    - https://www.nuget.org/packages/NuGet.Packaging.Core.Types/4.0.0
    - https://www.nuget.org/packages/NuGet.Frameworks/4.0.0
    - https://www.nuget.org/packages/NuGet.Versioning/4.0.0
2. Unpack them 
3. Take the dlls from `lib\net45` 
4. Place those files in `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Nuproj` or the equivalent in your Visual Studio install path.

Now, I'm not sure why I'm doing this... **you've been really rude in both your posts**. If you expect some help from the community you definetely should **review your manners**. People involved in this kind of open source projects (no matter whether is the developers, contributors or simply users sharing ideas) are doing this by vocation, so the least you could do is show some respect for them. And if you find that the product is not good enough you're totally free to get some other alternative or even build yours.

Cheers

**Comment by BjoernHund** [comment]
@dmalanij good comment

**Comment by JacksReacher** [comment]
@dmalanij Thanks for your assistance. Unfortunately, that didn't resolve the issue completely. 

If you checked "include source files in pdb", you'll get the error: 
_The "ReadPdbSourceFiles" task failed unexpectedly_

Seems if you run: regsvr32.exe "%VSINSTALLDIR%\Common7\IDE\msdia120.dll It will resolve it.
