### ISSUE TITLE
Could not load file or assembly 'NuGet.Packaging, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.

### ISSUE THREAD

**Issue by SimonSDA** [nuproj/nuproj#301]
When attempting to create a nuproj file for a 3rd party DLL (in this case an old Infragistics DLL) I get the error in the title. Here is the nuproj file:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|AnyCPU">
      <Configuration>Debug</Configuration>
      <Platform>AnyCPU</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|AnyCPU">
      <Configuration>Release</Configuration>
      <Platform>AnyCPU</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <ProjectGuid>456b065f-c604-439b-9a7c-e2c0ac827b55</ProjectGuid>
  </PropertyGroup>
  <PropertyGroup>
    <NuProjPath Condition=" '$(NuProjPath)' == '' ">$(MSBuildExtensionsPath)\NuProj\</NuProjPath>
  </PropertyGroup>
  <Import Project="$(NuProjPath)\NuProj.props" Condition="Exists('$(NuProjPath)\NuProj.props')" />
  <PropertyGroup Label="Configuration">
    <Id>Infragistics35.WebUI</Id>
    <Version>8.2.20082.1000</Version>
    <Title>Infragistics35.WebUI</Title>
    <Authors>Test</Authors>
    <Owners>Test</Owners>
    <Summary>Infragistics35.WebUI</Summary>
    <Description>Infragistics35.WebUI</Description>
    <ReleaseNotes>
    </ReleaseNotes>
    <ProjectUrl>
    </ProjectUrl>
    <LicenseUrl>
    </LicenseUrl>
    <Copyright>Copyright © Test</Copyright>
    <Tags>Infragistics35.WebUI</Tags>
    <OutputPath>C:\Git\Packages</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="lib\Infragistics35.WebUI.Shared.v8.2.dll" />
    <Content Include="Readme.txt" />
  </ItemGroup>
  <Import Project="$(NuProjPath)\NuProj.targets" />
</Project>
```

I am using Visual Studio Enterprise 2017 15.7.1

Two errors occur:

**Severity	Code	Description	Project	File	Line	Suppression State**
Error		Could not load file or assembly 'NuGet.Packaging, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.	Infragistics35.WebUI	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\NuProj\NuProj.targets	499	

**Severity	Code	Description	Project	File	Line	Suppression State**
Error		System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Packaging, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'NuGet.Packaging, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at NuProj.Tasks.GenerateNuSpec.WriteNuSpecFile()
   at NuProj.Tasks.GenerateNuSpec.Execute()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
	Infragistics35.WebUI	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\NuProj\NuProj.targets	499

**Comment by ivan-sam** [comment]
I have similar issue for NuProj projects created using Visual Studio 2017 and NuProj VS extension version 0.20.9.13653. The stack trace is a bit different:

```
Error	MSB4018	The "AssignTargetFramework" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Frameworks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'NuGet.Frameworks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at NuProj.Tasks.AssignTargetFramework.ConvertToPackageFile(ITaskItem output)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NuProj.Tasks.AssignTargetFramework.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

TestProjNuGet	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\NuProj\NuProj.targets	376	
```

The problem is that such projects refer `<NuProjPath Condition=" '$(NuProjPath)' == '' ">$(MSBuildExtensionsPath)\NuProj\</NuProjPath>`

Here is the content of that folder:
```
       300,776 Microsoft.Build.Utilities.v12.0.dll
         2,330 Microsoft.Common.NuProj.targets
     4,266,712 NuGet.exe
         2,353 NuProj.props
        51,108 NuProj.targets
        46,592 NuProj.Tasks.dll
<DIR>          Rules
```

And here's the content of NuProj package tools folder (which is referenced if you're following this steps: https://github.com/nuproj/nuproj/blob/master/docs/Build.md):
```
       101,768 Microsoft.Build.Framework.dll
       300,800 Microsoft.Build.Utilities.v12.0.dll
         2,330 Microsoft.Common.NuProj.targets
        81,600 Microsoft.Web.XmlTransform.dll
       548,528 NuGet.Core.dll
     3,955,928 NuGet.exe
         2,297 NuProj.props
        51,108 NuProj.targets
        43,520 NuProj.Tasks.dll
        81,408 NuProj.Tasks.pdb
<DIR>          Rules
```

so three dlls are missing in VS extension folder:
- Microsoft.Build.Framework.dll
- Microsoft.Web.XmlTransform.dll 
- NuGet.Core.dll

It could be that VS extension is using older version of NuProj dlls or some dlls are missing in installer.
The workaround is to reference NuProj package as documentation suggests.

However the best approach I can see is to change VS extension so it would create a project the same way as it's described in https://github.com/nuproj/nuproj/blob/master/docs/Build.md:

1. Create a projects and packages.config file that reference NuProj
2. Call NuGet restore in order to restore NuProj package or copy NuProj package into solution packages folder if it's not there (will work offline as well)

**Comment by jorgy343** [comment]
For my NuProj project to compile I had to reference the 0.20.4-beta nuget package. My .nuproj file thus contains
```
<NuProjPath>..\packages\NuProj.0.20.4-beta\tools\</NuProjPath>
```
